version: '2'

services:
  pg_db:
    image: postgres:latest
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env.db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  pgadmin: 
    image: dpage/pgadmin4
    ports: 
      - 5050:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    env_file:
      - .env.pgadmin
    depends_on:
      - pg_db
      
volumes:
  pgdata:
  pgadmindata:

