create table FavouriteGerichte (
       person_id int8 not null,
        gericht_id int8 not null,
        primary key (gericht_id, person_id)
    )
 
    
create table Gericht (
    id int8 generated by default as identity,
    ImageUrl varchar(255),
    Name varchar(255),
    rezept varchar(1200),
    primary key (id)
)


create table GerichteListeElement (
    id int8 generated by default as identity,
    gerichtId int8,
    sequence int8,
    tagesplan_localDate date,
    tagesplan_personId int8,
    primary key (id)
)


create table Lebensmittel (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
)


create table Person (
    id int8 generated by default as identity,
    email varchar(255),
    password bytea,
    salt bytea,
    uniqueSessionCode bytea,
    primary key (id)
)


create table Tagesplan (
    localDate date not null,
    personId int8 not null,
    primary key (localDate, personId)
)


create table Zutaten (
    id int8 not null,
    amount float8,
    messart varchar(255),
    gericht_id int8 not null,
    lebensmittel_id int8,
    primary key (gericht_id, id)
)

alter table if exists Person 
       add constraint UK_585qcyc8qh7bg1fwgm1pj4fus unique (email)
 
    
alter table if exists FavouriteGerichte 
    add constraint FK85qo3s8sqd3bj3fqtltj9wqjr 
    foreign key (person_id) 
    references Person 
    on delete cascade
 

alter table if exists FavouriteGerichte 
    add constraint FK4u02k5vuouu4qunvdhis43vki 
    foreign key (gericht_id) 
    references Gericht 
    on delete cascade
 

alter table if exists GerichteListeElement 
    add constraint FKk8cg2jqhqxfgno536cevq2tyw 
    foreign key (tagesplan_localDate, tagesplan_personId) 
    references Tagesplan 
    on delete cascade
 

alter table if exists Zutaten 
    add constraint FKcm897hy74puv3db9pblsvbsfh 
    foreign key (gericht_id) 
    references Gericht 
    on delete cascade
 

alter table if exists Zutaten 
    add constraint FK8d0073b7fu02cvm97wvb1whpi 
    foreign key (lebensmittel_id) 
    references Lebensmittel

insert into gericht (name, rezept) values ('Gong Bao', 'Das Rezept stammt von einer Chinareise aus der Stadt Chongqing.

Zun�chst den Boden des Wok gro�z�gig mit �l bedecken und dieses auf h�chster Stufe erhitzen. Das Geschnetzelte rundherum mit Mehl best�uben und im Wok scharf anbraten, dann salzen. Das Fleisch herausnehmen, evtl. etwas �l nachgeben und die gehackten Erdn�sse leicht anbraten. Die Erdn�sse herausnehmen und die Zwiebeln anbraten. Anschlie�end den gehackten Knoblauch hinzugeben und ebenfalls anbraten. Die Fr�hlingszwiebeln und die Chilischoten in Streifen schneiden und hinzugeben. Den Zucker dar�ber streuen und karamellisieren lassen.

Fleisch und Erdn�sse wieder hinzugeben. Mit Wein abl�schen, aufkochen lassen und den Essig hinzugeben. Abschlie�end mit Sojasauce, Ingwer und Pfeffer (gut zerkleinern, sehr intensiv!) w�rzen und abschmecken.

Auf Reis servieren.'),        ('K�sekr�ner', null ),         ('Leckeres zeug', null ),        ('Gong Be', null)